# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_widget(object):
    def setupUi(self, input_widget):
        input_widget.setObjectName("input_widget")
        input_widget.resize(445, 388)
        self.verticalLayout = QtWidgets.QVBoxLayout(input_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flair_file_widget = QtWidgets.QWidget(input_widget)
        self.flair_file_widget.setObjectName("flair_file_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.flair_file_widget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.flair_file_button = QtWidgets.QPushButton(self.flair_file_widget)
        self.flair_file_button.setObjectName("flair_file_button")
        self.horizontalLayout.addWidget(self.flair_file_button)
        self.flair_file_label = QtWidgets.QLabel(self.flair_file_widget)
        self.flair_file_label.setText("")
        self.flair_file_label.setObjectName("flair_file_label")
        self.horizontalLayout.addWidget(self.flair_file_label)
        self.verticalLayout.addWidget(self.flair_file_widget)
        self.glistrboost_file_widget = QtWidgets.QWidget(input_widget)
        self.glistrboost_file_widget.setObjectName("glistrboost_file_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.glistrboost_file_widget)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.glistrboost_file_button = QtWidgets.QPushButton(self.glistrboost_file_widget)
        self.glistrboost_file_button.setObjectName("glistrboost_file_button")
        self.horizontalLayout_2.addWidget(self.glistrboost_file_button)
        self.glistrbosst_file_label = QtWidgets.QLabel(self.glistrboost_file_widget)
        self.glistrbosst_file_label.setText("")
        self.glistrbosst_file_label.setObjectName("glistrbosst_file_label")
        self.horizontalLayout_2.addWidget(self.glistrbosst_file_label)
        self.verticalLayout.addWidget(self.glistrboost_file_widget)
        self.t1_file_widget = QtWidgets.QWidget(input_widget)
        self.t1_file_widget.setObjectName("t1_file_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.t1_file_widget)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.t1_file_button = QtWidgets.QPushButton(self.t1_file_widget)
        self.t1_file_button.setObjectName("t1_file_button")
        self.horizontalLayout_3.addWidget(self.t1_file_button)
        self.t1_file_label = QtWidgets.QLabel(self.t1_file_widget)
        self.t1_file_label.setText("")
        self.t1_file_label.setObjectName("t1_file_label")
        self.horizontalLayout_3.addWidget(self.t1_file_label)
        self.verticalLayout.addWidget(self.t1_file_widget)
        self.t1gd_file_widget = QtWidgets.QWidget(input_widget)
        self.t1gd_file_widget.setObjectName("t1gd_file_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.t1gd_file_widget)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.t1gd_file_button = QtWidgets.QPushButton(self.t1gd_file_widget)
        self.t1gd_file_button.setObjectName("t1gd_file_button")
        self.horizontalLayout_4.addWidget(self.t1gd_file_button)
        self.t1gd_file_label = QtWidgets.QLabel(self.t1gd_file_widget)
        self.t1gd_file_label.setText("")
        self.t1gd_file_label.setObjectName("t1gd_file_label")
        self.horizontalLayout_4.addWidget(self.t1gd_file_label)
        self.verticalLayout.addWidget(self.t1gd_file_widget)
        self.t2_file_widget = QtWidgets.QWidget(input_widget)
        self.t2_file_widget.setObjectName("t2_file_widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.t2_file_widget)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.t2_file_button = QtWidgets.QPushButton(self.t2_file_widget)
        self.t2_file_button.setObjectName("t2_file_button")
        self.horizontalLayout_5.addWidget(self.t2_file_button)
        self.t2_file_label = QtWidgets.QLabel(self.t2_file_widget)
        self.t2_file_label.setText("")
        self.t2_file_label.setObjectName("t2_file_label")
        self.horizontalLayout_5.addWidget(self.t2_file_label)
        self.verticalLayout.addWidget(self.t2_file_widget)

        self.retranslateUi(input_widget)
        QtCore.QMetaObject.connectSlotsByName(input_widget)

    def retranslateUi(self, input_widget):
        _translate = QtCore.QCoreApplication.translate
        input_widget.setWindowTitle(_translate("input_widget", "Form"))
        self.flair_file_button.setText(_translate("input_widget", "Select Flair"))
        self.glistrboost_file_button.setText(_translate("input_widget", "Select Glistrboost"))
        self.t1_file_button.setText(_translate("input_widget", "Select T1"))
        self.t1gd_file_button.setText(_translate("input_widget", "Select T1GD"))
        self.t2_file_button.setText(_translate("input_widget", "Select T2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    input_widget = QtWidgets.QWidget()
    ui = Ui_input_widget()
    ui.setupUi(input_widget)
    input_widget.show()
    sys.exit(app.exec_())
