# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1035, 801)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.input_and_setting = QtWidgets.QWidget(self.centralwidget)
        self.input_and_setting.setObjectName("input_and_setting")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.input_and_setting)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3.addWidget(self.input_and_setting)
        self.equation_frame = QtWidgets.QFrame(self.centralwidget)
        self.equation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.equation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.equation_frame.setObjectName("equation_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.equation_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3.addWidget(self.equation_frame)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1035, 23))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Glimoa Growth Visualization"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
