# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setting_widget(object):
    def setupUi(self, setting_widget):
        setting_widget.setObjectName("setting_widget")
        setting_widget.resize(501, 362)
        self.verticalLayout = QtWidgets.QVBoxLayout(setting_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_toggle = QtWidgets.QWidget(setting_widget)
        self.image_toggle.setObjectName("image_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.image_toggle)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.flair_rb = QtWidgets.QRadioButton(self.image_toggle)
        self.flair_rb.setObjectName("flair_rb")
        self.verticalLayout_2.addWidget(self.flair_rb)
        self.t1_rb = QtWidgets.QRadioButton(self.image_toggle)
        self.t1_rb.setObjectName("t1_rb")
        self.verticalLayout_2.addWidget(self.t1_rb)
        self.t1gd_rb = QtWidgets.QRadioButton(self.image_toggle)
        self.t1gd_rb.setObjectName("t1gd_rb")
        self.verticalLayout_2.addWidget(self.t1gd_rb)
        self.t2_rb = QtWidgets.QRadioButton(self.image_toggle)
        self.t2_rb.setObjectName("t2_rb")
        self.verticalLayout_2.addWidget(self.t2_rb)
        self.verticalLayout.addWidget(self.image_toggle)
        self.toggle_rb = QtWidgets.QRadioButton(setting_widget)
        self.toggle_rb.setObjectName("toggle_rb")
        self.verticalLayout.addWidget(self.toggle_rb)
        self.start_button = QtWidgets.QPushButton(setting_widget)
        self.start_button.setObjectName("start_button")
        self.verticalLayout.addWidget(self.start_button, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(setting_widget)
        QtCore.QMetaObject.connectSlotsByName(setting_widget)

    def retranslateUi(self, setting_widget):
        _translate = QtCore.QCoreApplication.translate
        setting_widget.setWindowTitle(_translate("setting_widget", "Form"))
        self.flair_rb.setText(_translate("setting_widget", "FLAIR"))
        self.t1_rb.setText(_translate("setting_widget", "TI"))
        self.t1gd_rb.setText(_translate("setting_widget", "T1GD"))
        self.t2_rb.setText(_translate("setting_widget", "T2"))
        self.toggle_rb.setText(_translate("setting_widget", "Toggle Overlay"))
        self.start_button.setText(_translate("setting_widget", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setting_widget = QtWidgets.QWidget()
    ui = Ui_setting_widget()
    ui.setupUi(setting_widget)
    setting_widget.show()
    sys.exit(app.exec_())
